### ISSUE TITLE
Scrolling issue on mobile

### ISSUE THREAD

**Issue by naveenjujaray** [palak-sethi/CodeDecode#1]
Unable to scroll to decode on mobile devices but able to do it by switching on desktop mode.

![ezgif.com-gif-maker.gif](https://user-images.githubusercontent.com/44742201/90686732-691b1180-e289-11ea-9163-6a98dfa909f5.gif)

**Comment by palak-sethi** [comment]
Thanks :) Adding overflow scroll to the body fixes the issue you mentioned. Would you like to provide a fix?

**Comment by naveenjujaray** [comment]
Sure I'll provide the fix.
