### ISSUE TITLE
Decode not visible on laptop

### ISSUE THREAD

**Issue by PulkitBanta** [palak-sethi/CodeDecode#3]
Reproduce - Click on the `Decode` button.

Error - the decode element gets out of the view port.

Example -
![image](https://user-images.githubusercontent.com/43134750/94819615-181c4280-041d-11eb-94b5-3279e379478d.png)

**Comment by palak-sethi** [comment]
Great find, would you like to work on fixing the issue?

**Comment by PulkitBanta** [comment]
Yes, assign this issue to me and I will work on this.
